/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: shedmon (https://sketchfab.com/shedmon)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/beanie-hat-25cb3b0549d049dfb4f180c81e43be90
title: Beanie Hat
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/model/hat/beanie_hat/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} position={[0, 1.15, -0.21]} scale={[0.0095, 0.01, 0.01]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/model/hat/beanie_hat/scene.gltf')

export {Model}
