/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Dokono Kinokoda (https://sketchfab.com/JunkWren)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/glasses-2-e009982029d84569b653614784e0457d
title: Glasses 2
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/model/glasses/glasses3/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale = {[0.65, 0.75, 0.5]} position = {[0, 0.15, 0.6]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.material_4} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Default_Material} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Default_Material} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Default_Material} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Default_Material} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Translucent_Glass_Tinted1} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.material_3} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.material_3} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.material_3} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.material_5} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.material_6} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.material_7} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.material_8} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.material_9} />
      </group>
    </group>
  )
}

useGLTF.preload('/model/glasses/glasses3/scene.gltf')

export {Model}