/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Marius.Eder (https://sketchfab.com/Marius.Eder)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/glasses-007651a9450746a5b6c5a126d484cd52
title: Glasses
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/model/glasses/glasses/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={[0.65, 0.65, 0.65]} position={[0, 0.3, 0.535]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_5.geometry} material={materials.Frame} />
          <mesh geometry={nodes.Object_7.geometry} material={materials.Handles} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/model/glasses/glasses/scene.gltf')

export {Model}
