/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: bashar-ALghaneem (https://sketchfab.com/bashar-ALghaneem)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/gold-chain-228fb92aea534a8dbf15c42c2d25f54b
title: Gold Chain
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/model/necklace/gold_chain/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI * (0.35), Math.PI * (1.40), Math.PI * (1.122)]} position={[-0.05,-0.8,-0.3]} scale={[0.0020, 0.0010, 0.0015]}>
          <group position={[901.89, 169.64, -282.66]} rotation={[-Math.PI, -0.31, 3.01]} />
          <group position={[0, 3.46, 0]}>
            <group position={[-433.72, 0, -263.92]} rotation={[0, 0.53, 0]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[-398.94, 0, -284.38]} rotation={[0, 0.53, 0]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_2_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_2_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[-363.81, 0, -304.21]} rotation={[0, 0.44, 0]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_3_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_3_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[-327.27, 0, -321.34]} rotation={[0, 0.44, 0]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_4_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_4_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[-289.37, 0, -335.16]} rotation={[0, 0.28, 0]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_5_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_5_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[-250.36, 0, -345.31]} rotation={[0, 0.08, 0]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_6_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_6_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[-210.07, 0, -347.61]} rotation={[0, 0.06, 0]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_7_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_7_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[-169.79, 0, -350.03]} rotation={[0, 0.06, 0]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_8_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_8_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[-129.5, 0, -352.44]} rotation={[0, 0.04, 0]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_9_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_9_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[-89.18, 0, -354.24]} rotation={[0, 0.04, 0]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_10_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_10_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[-48.86, 0, -356.04]} rotation={[0, 0.04, 0]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_11_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_11_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[-8.52, 0, -356.98]} rotation={[0, -0.01, 0]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_12_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_12_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[31.68, 0, -354.57]} rotation={[0, -0.21, 0]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_13_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_13_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[69.1, 0, -340.25]} rotation={[0, -0.55, 0]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_14_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_14_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[97.1, 0, -311.56]} rotation={[0, -0.97, 0]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_15_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_15_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[117.33, 0, -276.68]} rotation={[0, -1.1, 0]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_16_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_16_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[135.97, 0, -240.9]} rotation={[0, -1.02, 0]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_17_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_17_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[158.28, 0, -207.35]} rotation={[0, -0.9, 0]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_18_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_18_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[188.74, 0, -181.08]} rotation={[0, -0.61, 0]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_19_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_19_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[225.54, 0, -164.89]} rotation={[0, -0.28, 0]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_20_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_20_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[265.36, 0, -158.48]} rotation={[0, -0.15, 0]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_21_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_21_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[305.39, 0, -153.35]} rotation={[0, -0.13, 0]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_22_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_22_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[342.74, 0, -138.81]} rotation={[0, -0.52, 0]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_23_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_23_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[374.46, 0, -114.07]} rotation={[0, -0.78, 0]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_24_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_24_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[399.31, 0, -82.41]} rotation={[0, -0.99, 0]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_25_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_25_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[416.62, 0, -46.04]} rotation={[0, -1.28, 0]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_26_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_26_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[425.5, 0, -6.76]} rotation={[0, -1.48, 0]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_27_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_27_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[425.08, 0, 33.47]} rotation={[Math.PI, -1.45, Math.PI]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_28_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_28_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[413.12, 0, 71.81]} rotation={[Math.PI, -1.07, Math.PI]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_29_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_29_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[390.82, 0, 105.31]} rotation={[Math.PI, -0.86, Math.PI]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_30_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_30_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[361.71, 0, 133.13]} rotation={[Math.PI, -0.66, Math.PI]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_31_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_31_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[328.36, 0, 155.78]} rotation={[Math.PI, -0.57, Math.PI]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_32_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_32_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[292.53, 0, 174.33]} rotation={[Math.PI, -0.47, Math.PI]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_33_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_33_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[255.63, 0, 190.66]} rotation={[Math.PI, -0.4, Math.PI]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_34_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_34_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[218.26, 0, 205.89]} rotation={[Math.PI, -0.37, Math.PI]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_35_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_35_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[180.46, 0, 220.01]} rotation={[Math.PI, -0.35, Math.PI]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_36_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_36_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[142.54, 0, 233.83]} rotation={[Math.PI, -0.35, Math.PI]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_37_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_37_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[104.62, 0, 247.65]} rotation={[Math.PI, -0.35, Math.PI]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_38_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_38_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[65.83, 0, 258.54]} rotation={[Math.PI, -0.23, Math.PI]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_39_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_39_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[25.9, 0, 263.94]} rotation={[Math.PI, -0.04, Math.PI]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_40_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_40_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[-14.35, 0, 262.56]} rotation={[Math.PI, 0.16, -Math.PI]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_41_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_41_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[-53.72, 0, 253.88]} rotation={[Math.PI, 0.34, -Math.PI]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_42_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_42_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[-91.37, 0, 239.42]} rotation={[Math.PI, 0.44, -Math.PI]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_43_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_43_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[-127.69, 0, 221.85]} rotation={[Math.PI, 0.5, -Math.PI]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_44_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_44_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[-163.04, 0, 202.39]} rotation={[Math.PI, 0.53, -Math.PI]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_45_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_45_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[-197.91, 0, 182.06]} rotation={[Math.PI, 0.53, -Math.PI]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_46_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_46_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[-232.19, 0, 160.8]} rotation={[Math.PI, 0.59, Math.PI]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_47_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_47_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[-265.73, 0, 138.34]} rotation={[Math.PI, 0.59, Math.PI]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_48_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_48_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[-298.53, 0, 114.84]} rotation={[Math.PI, 0.64, -Math.PI]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_49_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_49_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[-330.96, 0, 90.82]} rotation={[Math.PI, 0.64, -Math.PI]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_50_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_50_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[-363.4, 0, 66.8]} rotation={[Math.PI, 0.64, -Math.PI]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_51_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_51_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[-397.13, 0, 44.75]} rotation={[Math.PI, 0.53, -Math.PI]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_52_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_52_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[-430.73, 0, 22.47]} rotation={[Math.PI, 0.62, -Math.PI]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_53_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_53_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[-461.84, 0, -3.18]} rotation={[Math.PI, 0.72, -Math.PI]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_54_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_54_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[-489.24, 0, -32.73]} rotation={[Math.PI, 0.92, -Math.PI]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_55_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_55_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[-511.37, 0, -66.38]} rotation={[Math.PI, 1.12, -Math.PI]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_56_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_56_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[-525.45, 0, -104.07]} rotation={[Math.PI, 1.37, -Math.PI]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_57_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_57_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[-527.92, 0, -144.19]} rotation={[0, 1.53, 0]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_58_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_58_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[-519.86, 0, -183.6]} rotation={[0, 1.25, 0]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_59_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_59_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[-500.13, 0, -218.45]} rotation={[0, 0.84, 0]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_60_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_60_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
            <group position={[-468.18, 0, -242.89]} rotation={[0, 0.6, 0]}>
              <group position={[12, -1.42, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh geometry={nodes['2_61_Mat_0'].geometry} material={materials.material} />
              </group>
              <group position={[-12, 1.42, 0]}>
                <mesh geometry={nodes['1_61_Mat_0'].geometry} material={materials.material} />
              </group>
            </group>
          </group>
        </group>
      </group>
  )
}

useGLTF.preload('/model/necklace/gold_chain/scene.gltf')

export {Model}