/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: cedeon (https://sketchfab.com/cedeon)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/gothic-pendant-necklace-da1b584886b94a7fb9c98dd642a319b3
title: Gothic Pendant Necklace
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/model/necklace/gothic_pendant_necklace/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
        <group position={[0, -1.78, -0.043]} rotation={[Math.PI * (0.3), 0, 0]} scale={[0.008, 0.007, 0.0062]}>
          <group position={[407.62, 590.39, -100.55]} rotation={[1.89, 0.88, -2.05]} scale={100}>
            <group rotation={[Math.PI / 2, 0, 0]} />
          </group>
          <group position={[735.89, 495.83, 692.58]} rotation={[Math.PI, 0.76, 2.68]} scale={100} />
          <group position={[1.08, 40.89, -185.82]} rotation={[-Math.PI / 2, 0, 0]} scale={697.69}>
            <group scale={0.79}>
              <mesh geometry={nodes.chain1_M_Chrome_0.geometry} material={materials.M_Chrome} />
            </group>
            <group position={[0, -0.24, -0.06]} rotation={[0, -Math.PI / 2, 0]} scale={1.05}>
              <mesh geometry={nodes.chain1001_M_Chrome_0.geometry} material={materials.M_Chrome} />
            </group>
          </group>
          <group rotation={[-1.62, -0.01, Math.PI / 2]} scale={[100, 100, 38.35]}>
            <mesh geometry={nodes.PendantGothic_M_Pendant_LP_0.geometry} material={materials.M_Pendant_LP} />
          </group>
        </group>
      </group>
  )
}

useGLTF.preload('/model/necklace/gothic_pendant_necklace/scene.gltf')

export {Model};