/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: torchwurm (https://sketchfab.com/torchwurm)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/head-base-mesh-660e8173c2014cc48a785caf862da7a6
title: Head Base Mesh
*/

import * as THREE from "three"; 
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/model/head_base_mesh/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null} rotation={[0, 0, 0]} position={[0, -0.1435, 0]} scale={[1, 1, 1]}>
      <group>
        <mesh geometry={nodes.Head_basemesh_0.geometry} material={hiderMat} />
      </group>
    </group>
  )
}

const hiderMat = new THREE.MeshPhongMaterial({
  attach: 'material',
  color: 'hotpink',
  colorWrite: false,
  renderOrder: 1,
});

useGLTF.preload('/model/head_base_mesh/scene.gltf');

export {Model};