/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: SimpleMan (https://sketchfab.com/postal1443)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/jashin-necklace-028988c5cc7b49c0addeb93bf3a6ff0f
title: Jashin Necklace
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/model/necklace/jashin_necklace/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, -1.8, -0.05]} rotation={[Math.PI * (1.45), 0, 0]} scale={[0.18, 0.155, 0.155]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_4.geometry} material={materials.Material} />
          <mesh geometry={nodes.Object_5.geometry} material={materials.Material} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/model/necklace/jashin_necklace/scene.gltf')

export {Model};
