/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Alexander Antipov (https://sketchfab.com/Dessen)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/male-head-0247a25a04ba46b99629130277fe39b7
title: Male Head
*/

import * as THREE from "three"
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/model/male_head/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} position={[0, -1.21, 0]} scale={0.6}>
        <mesh geometry={nodes.Object_2.geometry} material={hiderMat} />
      </group>
    </group>
  )
}

const hiderMat = new THREE.MeshPhongMaterial({
  attach: 'material',
  color: 'hotpink',
  colorWrite: false,
  renderOrder: 1,
});

useGLTF.preload('/model/male_head/scene.gltf')

export {Model};