/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: mayamurad (https://sketchfab.com/mayamurad)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/large-earring-with-complex-nested-pattern-2ac1e9753c954144955909b9b1308b73
title: Large earring with complex nested pattern
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/model/earring/complex_nested_pattern_earring/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0.675, -0.100, -0.238]} rotation={[-Math.PI * (0.5), 0, 0]} scale={0.0022}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['Scene_-_Root']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['Scene_-_Root']} />
      </group>

      <group position={[-0.675, -0.100, -0.238]} rotation={[-Math.PI * (0.5), 0, 0]} scale={0.0022}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['Scene_-_Root']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['Scene_-_Root']} />
      </group>
    </group>
  )
}

useGLTF.preload('/model/earring/complex_nested_pattern_earring/scene.gltf')

export {Model}
