/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: DineshThennarasan (https://sketchfab.com/dineshthennarasan)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/swan-earring-39ba87f0e3be4269a7e0d9148e1025fc
title: Swan Earring
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/model/earring/swan_earring/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
        <group position={[0.670, -0.30, -0.295]} rotation={[Math.PI * (1), -Math.PI * (0.75), Math.PI * (1)]} scale={0.005}>
          <group position={[1.17, 34.46, 2.07]} rotation={[-Math.PI / 2, 0, 0]} scale={0.59}>
            <mesh geometry={nodes.Sphere002_Material003_0.geometry} material={materials['Material.003']} />
            <mesh geometry={nodes.Sphere002_wire_088144225001_0.geometry} material={materials['wire_088144225.001']} />
            <mesh geometry={nodes.Sphere002_Material001_0.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Sphere002_Blued_Steel_0.geometry} material={materials.Blued_Steel} />
          </group>
          <group position={[1.18, 35.51, 1.56]} rotation={[2.28, 1.5, 0.91]} scale={[0.64, 0.64, 0.53]}>
            <mesh geometry={nodes.BezierCurve004_silver_0.geometry} material={materials.silver} />
          </group>
        </group>
      </group>
  )
}

useGLTF.preload('/model/earring/swan_earring/scene.gltf')

export {Model};
