/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Dokono Kinokoda (https://sketchfab.com/JunkWren)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/glasses-2-e009982029d84569b653614784e0457d
title: Glasses 2
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7: THREE.Mesh
    Object_8: THREE.Mesh
    Object_9: THREE.Mesh
    Object_10: THREE.Mesh
    Object_11: THREE.Mesh
    Object_12: THREE.Mesh
    Object_13: THREE.Mesh
    Object_14: THREE.Mesh
    Object_15: THREE.Mesh
    Object_16: THREE.Mesh
  }
  materials: {
    material_4: THREE.MeshStandardMaterial
    Default_Material: THREE.MeshStandardMaterial
    Translucent_Glass_Tinted1: THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
    material_3: THREE.MeshStandardMaterial
    material_5: THREE.MeshStandardMaterial
    material_6: THREE.MeshStandardMaterial
    material_7: THREE.MeshStandardMaterial
    material_8: THREE.MeshStandardMaterial
    material_9: THREE.MeshStandardMaterial
  }
}

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/scene.gltf') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.material_4} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Default_Material} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Default_Material} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Default_Material} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Default_Material} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Translucent_Glass_Tinted1} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.material_3} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.material_3} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.material_3} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.material_5} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.material_6} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.material_7} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.material_8} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.material_9} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
