/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Dokono Kinokoda (https://sketchfab.com/JunkWren)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/glasses-d25f2b7d0b094eea960e7b6c5277e60e
title: Glasses
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    a_F05: THREE.Mesh
    a_F05_1: THREE.Mesh
    a_I05: THREE.Mesh
    a_B05: THREE.Mesh
    a_E08: THREE.Mesh
    a_A06: THREE.Mesh
    a_E04: THREE.Mesh
  }
  materials: {
    daz__F05: THREE.MeshStandardMaterial
    daz__I05: THREE.MeshStandardMaterial
    daz__B05: THREE.MeshStandardMaterial
    daz__E08: THREE.MeshStandardMaterial
    daz__A06: THREE.MeshStandardMaterial
    daz__E04: THREE.MeshStandardMaterial
  }
}

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/scene.gltf') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[14.99, 23.68, 57.69]} rotation={[-0.34, 0.08, 0.03]} />
          <group position={[10.01, 0.42, -0.03]}>
            <mesh geometry={nodes.a_F05.geometry} material={materials.daz__F05} />
            <mesh geometry={nodes.a_F05_1.geometry} material={materials.daz__F05} />
            <mesh geometry={nodes.a_I05.geometry} material={materials.daz__I05} />
            <mesh geometry={nodes.a_B05.geometry} material={materials.daz__B05} />
            <mesh geometry={nodes.a_E08.geometry} material={materials.daz__E08} />
            <mesh geometry={nodes.a_A06.geometry} material={materials.daz__A06} />
            <mesh geometry={nodes.a_E04.geometry} material={materials.daz__E04} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
