/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Marius.Eder (https://sketchfab.com/Marius.Eder)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/glasses-007651a9450746a5b6c5a126d484cd52
title: Glasses
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_5: THREE.Mesh
    Object_7: THREE.Mesh
    Object_9: THREE.Mesh
  }
  materials: {
    Frame: THREE.MeshStandardMaterial
    Handles: THREE.MeshStandardMaterial
    ['Frame.1']: THREE.MeshPhysicalMaterial
  }
}

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/scene.gltf') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.7}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_5.geometry} material={materials.Frame} />
          <mesh geometry={nodes.Object_7.geometry} material={materials.Handles} />
          <mesh geometry={nodes.Object_9.geometry} material={materials['Frame.1']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
